name: Tests By Symfony Version

on:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - main
      - 0.*
      - 1.*
  schedule:
    # Weekly on Thursdays at 3pm UTC
    - cron:  '0 15 * * 4'

jobs:
  symfony70:
    uses: mrgoodbytes8667/workflows/.github/workflows/run-tests-by-version.yml@php8.2-8.3
    with:
      phpUnitVersion: 9.6
      symfony: 7.0
      setupPhpExtensions: ", imagick"

  symfony71:
    uses: mrgoodbytes8667/workflows/.github/workflows/run-tests-by-version.yml@php8.2-8.3
    with:
      phpUnitVersion: 9.6
      symfony: 7.1
      setupPhpExtensions: ", imagick"

  symfony72:
    uses: mrgoodbytes8667/workflows/.github/workflows/run-tests-by-version.yml@php8.2-8.3
    with:
      phpUnitVersion: 9.6
      symfony: 7.2
      setupPhpExtensions: ", imagick"
      minStability: dev